# Generated by Django 5.0.7 on 2024-08-11 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('مفتوح', 'مفتوح'), ('تحت الإجراء', 'تحت الإجراء'), ('منتهي', 'منتهي')], default='مفتوح', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_type', models.CharField(max_length=255)),
                ('printer_id', models.CharField(max_length=100)),
                ('ink_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('مفتوح', 'مفتوح'), ('تحت الإجراء', 'تحت الإجراء'), ('منتهي', 'منتهي')], default='مفتوح', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsupport.maintenancerequest')),
                ('user_request_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsupport.printerrequest')),
            ],
        ),
    ]
