# Generated by Django 5.0.7 on 2024-07-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
