# Generated by Django 5.0.7 on 2024-08-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ithelp',
            name='user_request_p',
        ),
    ]
