# Generated by Django 5.0.7 on 2024-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0002_delete_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('sendit', 'أرسل'), ('pending', 'تحت الإجراء'), ('completed', 'منفذ')], default='أرسل', max_length=20),
        ),
    ]
