# Generated by Django 5.0.7 on 2024-08-11 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0003_printerhelp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itsupport.maintenancerequest')),
                ('user_request_p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itsupport.printerrequest')),
            ],
        ),
    ]
