# Generated by Django 5.0.7 on 2024-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0003_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='device_model',
            new_name='device_id',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
