# Generated by Django 5.0.7 on 2024-08-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0004_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_request',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_request_p',
        ),
    ]
