# Generated by Django 5.0.7 on 2024-07-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0004_rename_device_model_maintenancerequest_device_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_type', models.CharField(max_length=255)),
                ('printer_id', models.CharField(max_length=100)),
                ('ink_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('sendit', 'أرسل'), ('pending', 'تحت الإجراء'), ('completed', 'منفذ')], default='أرسل', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
