# Generated by Django 5.0.7 on 2024-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0006_alter_printerrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('sendit', 'تم إرسال الطلب'), ('pending', 'تحت الإجراء'), ('completed', 'منفذ')], default='تم إرسال الطلب', max_length=20),
        ),
    ]
