# Generated by Django 5.0.7 on 2024-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0007_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('تم إرسال الطلب', 'sendit'), ('تحت الإجراء', 'pending'), ('منفذ', 'completed')], default='تم إرسال الطلب', max_length=20),
        ),
    ]
