# Generated by Django 5.0.7 on 2024-07-25 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0008_alter_maintenancerequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('مفتوح', 'sendit'), ('تحت الإجراء', 'pending'), ('منتهي', 'completed')], default='تم إرسال الطلب', max_length=20),
        ),
        migrations.CreateModel(
            name='ItHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsupport.maintenancerequest')),
            ],
        ),
    ]
