# Generated by Django 5.0.7 on 2024-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsupport', '0012_alter_printerrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerrequest',
            name='status',
            field=models.CharField(choices=[('مفتوح', 'مفتوح'), ('تحت الإجراء', 'تحت الإجراء'), ('منتهي', 'منتهي')], default='مفتوح', max_length=20),
        ),
    ]
